import Head from "next/head";
import styles from "@/styles/About.module.css";

import AppBar from "@/components/AppBar";

export default function About() {
  return (
    <>
      <Head>
        <title>About | type game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />
      <main className={styles.aboutPage}>
        <div className={styles.aboutHead}>
          <h1>
            About <code>type game</code>
          </h1>
          <h3>How fast can you type?</h3>
        </div>

        <div className={styles.aboutContainer}></div>
        <div className={styles.aboutFooter}></div>
      </main>
    </>
  );
}
