import Head from "next/head";
import styles from "@/styles/About.module.css";

import AppBar from "@/components/AppBar";
import Link from "next/link";

export default function About() {
  return (
    <>
      <Head>
        <title>About | type game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />
      <main className={styles.aboutPage}>
        <div className={styles.aboutHead}>
          <h1>
            About <code>type game</code>
          </h1>
          <h3>How fast can you type?</h3>
        </div>

        <div className={styles.aboutContainer}>
          <p>
            Welcome to &quot;type game&quot; – a fun and addictive game that
            challenges your typing skills! In this game, you&apos;ll be given a
            random phrase to type with the goal to type it as fast and
            accurately as you can. The game tracks your time and type count for
            each completed phrase, allowing you to measure and share progress.
          </p>
          <p>
            With the optional sign-in feature, you can also track and share your
            own high scores with friends and other players. Built with
            TypeScript, Next.js, and MongoDB, &quot;type game&quot; is fast,
            responsive, and easy to use.
          </p>
          <span className={styles.aboutBtns}>
            <Link href="/">Play Now!</Link>
            <Link href="/auth">Sign Up / Log in</Link>
          </span>
        </div>
        <div className={styles.aboutFooter}>
          <span>
            <p>
              If you want to learn more about how the game was built, or have
              any feedback or questions, visit the repository
            </p>
            <Link href="https://github.com/3derekmason/type-game">here.</Link>
          </span>
        </div>
      </main>
    </>
  );
}
