import Head from "next/head";
import styles from "@/styles/AuthPage.module.css";
import { useAppContext } from "../../context/state";
import { useState } from "react";

import AppBar from "../components/AppBar";

const AuthPage = () => {
  const { setCurrentAdmin, router } = useAppContext();
  const [username, setUsername] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [signup, setSignup] = useState<boolean>(true);
  return (
    <>
      <Head>
        <title>User Login | type game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />
      <main className={styles.authPage}>
        <span className={styles.authToggle}>
          <caption>Sign Up</caption>
          <div className={styles.btnHolster}>
            <button
              onClick={() => {
                setSignup(!signup);
              }}
              className={
                signup ? styles.toggleBtnSignup : styles.toggleBtnLogin
              }
            ></button>
          </div>
          <caption>Log In</caption>
        </span>
        {signup ? (
          <form>
            <h2>Sign Up</h2>
            <h4>Sign up to track high scores and join the community!</h4>
            <input type="text" placeholder="Username" />
            <input type="password" placeholder="Choose Password" />
            <button className={styles.submitBtn}>Sign Up</button>
          </form>
        ) : (
          <form>
            <h2>Log In</h2>
            <h4>Welcome back!</h4>
            <input type="text" placeholder="Username" />
            <input type="password" placeholder="Password" />
            <button className={styles.submitBtn}>Log In</button>
          </form>
        )}
      </main>
    </>
  );
};

export default AuthPage;
