import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useAppContext } from "../../context/state";

import AppBar from "@/components/AppBar";
import GameWord from "@/components/GameWord";
import { useEffect, useState } from "react";

export default function Home() {
  const { currentUser } = useAppContext();
  const [target, setTarget] = useState<string>("type game");

  const getRandomWord = () => {
    try {
      fetch("/api/words")
        .then((res) => res.json())
        .then((data) => setTarget(data.title));
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    getRandomWord();
  }, []);
  return (
    <>
      <Head>
        <title>type game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AppBar />
        <div className={styles.helloUser}>
          {currentUser ? <h2>{currentUser.username}</h2> : ""}
        </div>
        <GameWord targetWord={target} getRandomWord={getRandomWord} />
      </main>
    </>
  );
}
