import Head from "next/head";
import styles from "@/styles/HighScore.module.css";
import { useAppContext } from "../../context/state";

import AppBar from "@/components/AppBar";
import { useEffect, useState } from "react";

export default function HighScore() {
  const { currentUser } = useAppContext();
  const [publicScores, setPublicScores] = useState<any>();
  const getPublicScores = async () => {
    const endpoint = "/api/scores";
    const options = {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    };
    try {
      const response = await fetch(endpoint, options);
      const result = await response.json();
      setPublicScores(result);
    } catch (err: any) {
      console.error(err);
    }
  };

  useEffect(() => {
    getPublicScores();
  }, []);

  return (
    <>
      <Head>
        <title>High Scores | type game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />
      <main className={styles.highScorePage}>
        {publicScores?.map((score: any, i: number) => {
          return (
            <div key={i}>
              <p>{score.title}</p>
              <p>{score.time}s</p>
              <p>{score.count}</p>
            </div>
          );
        })}
      </main>
    </>
  );
}
