import Head from "next/head";
// import styles from "@/styles/Home.module.css";
import { useAppContext } from "../../context/state";
import Score from "@/interface/Score";

import AppBar from "@/components/AppBar";
import { ReactNode, useEffect, useState } from "react";

export default function User() {
  const { currentUser, router } = useAppContext();
  const [userScores, setUserScores] = useState<Score[]>([]);
  const [perfectScores, setPerfectScores] = useState<number>(0);
  const [perfectPercentage, setPerfectPercentage] = useState<number>(0);

  const getUserScores = () => {
    try {
      fetch(`/api/score/user/${currentUser._id}`)
        .then((res) => res.json())
        .then((data) => setUserScores(data));
    } catch (err) {
      console.error(err);
    }
    let perfect = 0;
    userScores.forEach((score) => {
      if (score.count === score.title.length) {
        perfect++;
      }
    });
    setPerfectScores(perfect);
    setPerfectPercentage((perfect / userScores.length) * 100);
  };

  const formatDate = (date: ReactNode) => {
    const string = JSON.stringify(date).split("T")[0];
    const dateString = string.slice(1).split("-");
    return `${dateString[1]}/${dateString[2]}/${dateString[0]}`;
  };

  useEffect(() => {
    if (!currentUser) {
      router.push("/auth");
    }
    getUserScores();
  }, []);

  return (
    <>
      <Head>
        <title>{currentUser?.username} | type game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar />
      <main style={{ color: "#ffffff" }}>
        <p>Completed: {userScores.length}</p>
        <p>
          Perfect Scores: {perfectScores} ({perfectPercentage.toFixed(2)}%)
        </p>
        {userScores.map((score, i) => {
          return (
            <span key={i}>
              <p>{score.title}</p>
              <p>{score.time}s</p>
              <p>
                {score.count} / {score.title.length}
              </p>
              <p>{formatDate(score.created_at)}</p>
            </span>
          );
        })}
      </main>
    </>
  );
}
